{% set name = "aws-cdk.custom-resources" %}
{% set version = "1.204.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aws-cdk.custom-resources-{{ version }}.tar.gz
  sha256: 43bd63d28a0a9e041d219cc12677ba505dfd21cfb4f9d72096b671cad07cf182

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=67.3.2,<67.4.dev0
    - wheel >=0.40,<1.dev0
    - pip
  run:
    - python >={{ python_min }}
    - aws-cdk.aws-cloudformation ==1.204.0
    - aws-cdk.aws-ec2 ==1.204.0
    - aws-cdk.aws-iam ==1.204.0
    - aws-cdk.aws-lambda ==1.204.0
    - aws-cdk.aws-logs ==1.204.0
    - aws-cdk.aws-sns ==1.204.0
    - aws-cdk.core ==1.204.0
    - constructs >=3.3.69,<4.0.0
    - python-jsii >=1.84.0,<2.0.0
    - publication >=0.0.3
    - typeguard >=2.13.3,<2.14.dev0

test:
  imports:
    - aws_cdk.custom_resources
    - aws_cdk.custom_resources._jsii
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aws/aws-cdk
  summary: Constructs for implementing CDK custom resources
  dev_url: https://github.com/aws/aws-cdk.git
  license: Apache-2.0
  license_file:
    - NOTICE
    - LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
